-- Table: public.bnc_bancos

-- DROP TABLE IF EXISTS public.bnc_bancos;

CREATE TABLE IF NOT EXISTS public.bnc_bancos
(
    cod_banco integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    recibe_dinero boolean NOT NULL,
    rowid uuid DEFAULT gen_random_uuid(),
    observaciones character varying(200) COLLATE pg_catalog."default",
    codigo character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT bnc_bancos_pkey PRIMARY KEY (cod_banco)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.bnc_bancos
    OWNER to postgres;