-- Table: public.historicomedicion

-- DROP TABLE IF EXISTS public.historicomedicion;

CREATE TABLE IF NOT EXISTS public.historicomedicion
(
    ide integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1119616 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ano numeric(4,0) NOT NULL,
    mes numeric(2,0) NOT NULL,
    contador character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    ciclo character(2) COLLATE pg_catalog."default" DEFAULT '0'::bpchar,
    ruta character(25) COLLATE pg_catalog."default" DEFAULT ''::bpchar,
    secuencia character(9) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    clave character(15) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    fecha date,
    usuario character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    lect_act numeric(12,0) DEFAULT NULL::numeric,
    lect_ant numeric(12,0) DEFAULT NULL::numeric,
    fecha_lect_act date,
    fecha_lect_ant date,
    hora time without time zone,
    consumo numeric(12,0) DEFAULT '0'::numeric,
    consumoant numeric(12,0) DEFAULT '0'::numeric,
    tservi1 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    taservi1 numeric(12,2) DEFAULT 0.00,
    tservi2 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    taservi2 numeric(12,2) DEFAULT 0.00,
    tservi3 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    taservi3 numeric(12,2) DEFAULT 0.00,
    tservi4 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    taservi4 numeric(12,2) DEFAULT 0.00,
    cerrado character(1) COLLATE pg_catalog."default" DEFAULT '0'::bpchar,
    ser1 character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    ser2 character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    ser3 character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    ser4 character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    comentario character varying(145) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    propietario character(100) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    ubicacion character(100) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    otros character(20) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    categoria character(1) COLLATE pg_catalog."default" DEFAULT '0'::bpchar,
    observacion character varying(300) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    mes2 character(2) COLLATE pg_catalog."default" DEFAULT ''::bpchar,
    condicion character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    lec_prom numeric(12,0) DEFAULT '0'::numeric,
    tipolectura character(1) COLLATE pg_catalog."default" DEFAULT ''::bpchar,
    codinfo character(2) COLLATE pg_catalog."default" DEFAULT ''::bpchar,
    ser5 character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    ser6 character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    ser7 character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    ser8 character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    ser9 character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    ser10 character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    tservi5 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    tservi6 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    tservi7 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    tservi8 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    tservi9 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    tservi10 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    taservi5 numeric(12,2) DEFAULT 0.00,
    taservi6 numeric(12,2) DEFAULT 0.00,
    taservi7 numeric(12,2) DEFAULT 0.00,
    taservi8 numeric(12,2) DEFAULT 0.00,
    taservi9 numeric(12,2) DEFAULT 0.00,
    taservi10 numeric(12,2) DEFAULT 0.00,
    revision numeric(1,0) DEFAULT '0'::numeric,
    orden character(1) COLLATE pg_catalog."default" DEFAULT '0'::bpchar,
    revision2 character(1) COLLATE pg_catalog."default" DEFAULT '0'::bpchar,
    sel numeric(1,0) DEFAULT '0'::numeric,
    numeroord numeric(12,0) DEFAULT '0'::numeric,
    ajuste character(2) COLLATE pg_catalog."default" DEFAULT ''::bpchar,
    numerofactura character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    correlativocai bigint,
    idcai bigint,
    imagenmedidor bytea,
    descuentoapp numeric(14,2) DEFAULT NULL::numeric,
    categoriacliente character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    CONSTRAINT historicomedicion_pkey PRIMARY KEY (ide)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.historicomedicion
    OWNER to postgres;