-- Table: public.identityuserclaim<string>

-- DROP TABLE IF EXISTS public."identityuserclaim<string>";

CREATE TABLE IF NOT EXISTS public."identityuserclaim<string>"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id text COLLATE pg_catalog."default" NOT NULL,
    claim_type text COLLATE pg_catalog."default",
    claim_value text COLLATE pg_catalog."default",
    CONSTRAINT pk_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_user_claims_asp_net_users_identity_user_id FOREIGN KEY (user_id)
        REFERENCES public.identityuser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."identityuserclaim<string>"
    OWNER to postgres;
-- Index: ix_user_claims_user_id

-- DROP INDEX IF EXISTS public.ix_user_claims_user_id;

CREATE INDEX IF NOT EXISTS ix_user_claims_user_id
    ON public."identityuserclaim<string>" USING btree
    (user_id COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;