-- Table: public.identityroleclaim<string>

-- DROP TABLE IF EXISTS public."identityroleclaim<string>";

CREATE TABLE IF NOT EXISTS public."identityroleclaim<string>"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    role_id text COLLATE pg_catalog."default" NOT NULL,
    claim_type text COLLATE pg_catalog."default",
    claim_value text COLLATE pg_catalog."default",
    CONSTRAINT pk_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_role_claims_asp_net_roles_identity_role_id FOREIGN KEY (role_id)
        REFERENCES public.identityrole (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."identityroleclaim<string>"
    OWNER to postgres;
-- Index: ix_role_claims_role_id

-- DROP INDEX IF EXISTS public.ix_role_claims_role_id;

CREATE INDEX IF NOT EXISTS ix_role_claims_role_id
    ON public."identityroleclaim<string>" USING btree
    (role_id COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;