-- Table: public.rutas

-- DROP TABLE IF EXISTS public.rutas;

CREATE TABLE IF NOT EXISTS public.rutas
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    codciclo integer,
    codruta character varying COLLATE pg_catalog."default",
    descripcion character varying COLLATE pg_catalog."default",
    CONSTRAINT rutas_fk FOREIGN KEY (codciclo)
        REFERENCES public.ciclos (ciclos_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.rutas
    OWNER to postgres;